### PR TITLE
Implementing edit text mask

### PR DESCRIPTION
**Pull request by dev-billy**
Added an edit text mask, which helps in inputting numbers with standardized formats.

**example**:
  1. Inputting a phone number with format +255(0)XXX-XXXXXX
  2. Inputting a passport number

This fix helps to define the mask on a new input field

### CODE REVIEW

**Comment by cozej4** [comment]
Hi @ellykits. Could you check this implementation and review the PR. 
This is a nice addition to the neat forms

**Comment by ellykits** [comment]
Noted @cozej4 I have been away for vacation but will resume soon.

**Review by ellykits — APPROVED** [review]

**Comment by ellykits** [comment]
:+1: LGTM squash merge your changes. Thanks for the contribution @dev-billy

**Comment by dev-billy** [comment]
Great, Thank you. Would love to get write access so I can squash merge the changes @ellykits

**Comment by ellykits** [comment]
I have merged the code.

**Comment by ellykits** [comment]
Also sent you an invite as a collaborator

**Comment by dev-billy** [comment]
Great👍🏾  
Thanks

**Pull request merged**
